repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        args:
          - --ignore=DL3006
          - --ignore=DL3008
          - --ignore=DL3013
          - --ignore=DL3015
          - --ignore=DL4006
          - --ignore=SC2028

  - repo: local
    hooks:
      - id: check-version-semver
        name: Check VERSION files are valid SemVer
        entry: scripts/check-version.sh
        language: script
        files: ^images/.*/VERSION$
