name: Build Ansible EE Images

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      VERSION: ""
      REGISTRY: ghcr.io/kiddingbaby

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute VERSION
        id: compute_version
        run: |
          if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            VERSION="dev-$(git rev-parse --short=7 HEAD)"
          fi

          if [ -z "${VERSION}" ]; then
            echo "错误: VERSION 参数丢失，构建终止！"
            exit 1
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Bake
        uses: docker/bake-action@v6
        env:
          VERSION: ${{ steps.compute_version.outputs.version }}
          GITHUB_SHA: ${{ github.sha }}
        with:
          files: docker-bake.hcl
          targets: all
          # push: ${{ github.event_name != 'pull_request' }}
          push: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
