name: Build Ansible EE Images

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      # Container registry
      REGISTRY: ghcr.io/kiddingbaby
      # docker-bake.hcl defines the targets
      TARGETS: default
      # Set to true for testing purposes, false for actual push
      FAKE_PUSH: true

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Compute VERSION
        id: compute_version
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" =~ refs/tags/(.*) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            VERSION="dev-$(git rev-parse --short=7 HEAD)"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "FAKE_PUSH=${FAKE_PUSH}"

      - name: Login registry
        if: env.FAKE_PUSH == 'false'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build EE images
        uses: docker/bake-action@v5
        with:
          files: docker-bake.hcl
          targets: ${{ env.TARGETS }}
          push: ${{ env.FAKE_PUSH == 'false' }}
          set: |
            *.args.VERSION=${{ steps.compute_version.outputs.version }}
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
